name: Compilar APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Reparar Estructura Automáticamente
        run: |
          flutter create . --overwrite --platforms=android

      - name: Construir APK
        run: |
          flutter pub get
          flutter build apk --release

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: app-futsal
          path: build/app/outputs/flutter-apk/app-release.apk
